export const UserActionTypes ={
    SET_CURRENT_USER:'SET_CURRENT_USER'
    // FETCH_COLLECTION_START : 'FETCH_COLLECTION_START',
    // FETCH_USER_SECCUSS : 'FETCH_USER_SECCUSS',
    // FETCH_USER_FAILURE : 'FETCH_USER_FAILURE'
}